<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Inertia\Inertia;
use Inertia\Response;

/**
 * Controller untuk mengelola Direktori Lokasi Klinik & Jaringan Rumah Sakit Publik.
 * Terinspirasi dari direktori klinik & RS Siloam Hospitals dengan standar desain Evergreen.
 */
class ClinicLocationController extends Controller
{
    /**
     * Menampilkan daftar cabang jaringan rumah sakit dan klinik publik.
     */
    public function index(Request $request): Response
    {
        // Daftar cabang klinik & rumah sakit jaringan Hospital Population
        $clinics = [
            [
                'id' => 1,
                'name' => 'Hospital Population Siloam Central Lippo',
                'slug' => 'central-lippo',
                'facility_type' => 'Rumah Sakit Utama',
                'category_badge' => 'RS Tipe A · Rujukan Nasional',
                'city' => 'Tangerang',
                'province' => 'Banten',
                'address' => 'Jl. Siloam No. 6, Lippo Karawaci, Tangerang, Banten 15811',
                'distance_info' => 'Pusat Rujukan Utama & Trauma Center 24 Jam',
                'operating_hours' => '24 Jam (IGD & Rawat Inap) · Poliklinik: 07.30 - 21.00 WIB',
                'phone' => '(021) 8052-9900',
                'whatsapp' => '0811-9988-7711',
                'emergency_24h' => true,
                'bed_capacity' => 320,
                'doctor_count' => 85,
                'google_maps_url' => 'https://maps.google.com/?q=Hospital+Population+Siloam+Central+Lippo+Karawaci',
                'available_polis' => [
                    'Poli Jantung & Pembuluh Darah',
                    'Poli Bedah & Ortopedi',
                    'Poli Anak & Tumbuh Kembang',
                    'Poli Penyakit Dalam',
                    'Poli Kebidanan & Kandungan',
                    'Poli Saraf & Bedah Saraf',
                    'Poli Mata',
                    'Poli Gigi & Mulut',
                ],
                'featured_facilities' => [
                    'IGD & Trauma Center 24 Jam',
                    'MRI 3.0 Tesla & CT-Scan 512 Slice',
                    'Cath Lab Jantung Modern',
                    'ICU / NICU / PICU',
                    'Farmasi & Laboratorium 24 Jam',
                ],
                'image_url' => 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'id' => 2,
                'name' => 'Hospital Population MRCCC Semanggi',
                'slug' => 'mrccc-semanggi',
                'facility_type' => 'Rumah Sakit Utama',
                'category_badge' => 'RS Khusus Kanker & Onkologi Terpadu',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'address' => 'Jl. Garnisun Kav. 2-3, Karet Semanggi, Setiabudi, Jakarta Selatan 12930',
                'distance_info' => 'Pusat Kanker Terpadu & Radioterapi Terkini',
                'operating_hours' => '24 Jam (IGD & Kemoterapi) · Poliklinik: 08.00 - 20.30 WIB',
                'phone' => '(021) 2996-2888',
                'whatsapp' => '0811-9988-7722',
                'emergency_24h' => true,
                'bed_capacity' => 240,
                'doctor_count' => 64,
                'google_maps_url' => 'https://maps.google.com/?q=Hospital+Population+MRCCC+Semanggi+Jakarta',
                'available_polis' => [
                    'Poli Penyakit Dalam & Hematologi',
                    'Poli Bedah Onkologi',
                    'Poli Bedah & Ortopedi',
                    'Poli Radiasi Onkologi',
                    'Poli Umum',
                    'Poli Saraf',
                ],
                'featured_facilities' => [
                    'Linear Accelerator (Linac) Radioterapi',
                    'PET-CT Scan 128 Slice',
                    'Pusat Kemoterapi One Day Care',
                    'Laboratorium Patologi Anatomi',
                    'IGD Onkologi 24 Jam',
                ],
                'image_url' => 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'id' => 3,
                'name' => 'Hospital Population TB Simatupang',
                'slug' => 'tb-simatupang',
                'facility_type' => 'Rumah Sakit Utama',
                'category_badge' => 'RS Tipe B · Pusat Kardiologi & Saraf',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'address' => 'Jl. TB Simatupang Kav. 36, Cilandak Barat, Jakarta Selatan 12430',
                'distance_info' => 'Akses Langsung Exit Tol TB Simatupang & MRT Fatmawati',
                'operating_hours' => '24 Jam (IGD & Rawat Inap) · Poliklinik: 08.00 - 21.00 WIB',
                'phone' => '(021) 2953-1900',
                'whatsapp' => '0811-9988-7733',
                'emergency_24h' => true,
                'bed_capacity' => 190,
                'doctor_count' => 58,
                'google_maps_url' => 'https://maps.google.com/?q=Hospital+Population+TB+Simatupang+Jakarta',
                'available_polis' => [
                    'Poli Jantung & Pembuluh Darah',
                    'Poli Saraf & Brain Center',
                    'Poli Anak & Tumbuh Kembang',
                    'Poli Penyakit Dalam',
                    'Poli Mata & Vitreoretina',
                    'Poli THT',
                ],
                'featured_facilities' => [
                    'IGD 24 Jam & Tim Ambulans Cepat',
                    'Unit Stroke & Cath Lab 24 Jam',
                    'Pusat Endoskopi Saluran Cerna',
                    'Layanan Fisioterapi & Rehabilitasi',
                    'Klinik Vaksinasi Internasional',
                ],
                'image_url' => 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'id' => 4,
                'name' => 'Hospital Population Kebon Jeruk',
                'slug' => 'kebon-jeruk',
                'facility_type' => 'Rumah Sakit Utama',
                'category_badge' => 'RS Tipe B · Pusat Ortopedi & Urologi',
                'city' => 'Jakarta Barat',
                'province' => 'DKI Jakarta',
                'address' => 'Jl. Raya Pejuang No. 8, Kebon Jeruk, Jakarta Barat 11530',
                'distance_info' => 'Dekat Tol Kebon Jeruk / Tomang & Area Bisnis',
                'operating_hours' => '24 Jam (IGD) · Poliklinik: 08.00 - 21.00 WIB',
                'phone' => '(021) 2567-7888',
                'whatsapp' => '0811-9988-7744',
                'emergency_24h' => true,
                'bed_capacity' => 210,
                'doctor_count' => 52,
                'google_maps_url' => 'https://maps.google.com/?q=Hospital+Population+Kebon+Jeruk+Jakarta',
                'available_polis' => [
                    'Poli Bedah & Ortopedi',
                    'Poli Kebidanan & Kandungan',
                    'Poli Penyakit Dalam',
                    'Poli Anak & Tumbuh Kembang',
                    'Poli Gigi & Mulut',
                    'Poli Umum',
                ],
                'featured_facilities' => [
                    'Pusat Bedah Minimal Invasif (Laparoskopi)',
                    'Pusat ESWL Pemecah Batu Ginjal',
                    'Layanan Medical Check-Up Eksekutif',
                    'Kamar Bedah Digital Terintegrasi',
                    'Layanan Hemodialisa 24 Mesin',
                ],
                'image_url' => 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'id' => 5,
                'name' => 'Klinik Utama Population Menteng',
                'slug' => 'klinik-menteng',
                'facility_type' => 'Klinik Utama',
                'category_badge' => 'Klinik Spesialis Eksekutif',
                'city' => 'Jakarta Pusat',
                'province' => 'DKI Jakarta',
                'address' => 'Jl. HOS Cokroaminoto No. 42, Menteng, Jakarta Pusat 10350',
                'distance_info' => 'Kawasan Pusat Menteng, Layanan One-Stop Medical Care',
                'operating_hours' => 'Senin - Sabtu: 07.30 - 20.00 WIB (Minggu: 08.00 - 14.00 WIB)',
                'phone' => '(021) 3192-4455',
                'whatsapp' => '0811-9988-7755',
                'emergency_24h' => false,
                'bed_capacity' => 0,
                'doctor_count' => 24,
                'google_maps_url' => 'https://maps.google.com/?q=Klinik+Utama+Population+Menteng+Jakarta+Pusat',
                'available_polis' => [
                    'Poli Umum',
                    'Poli Penyakit Dalam',
                    'Poli Anak & Tumbuh Kembang',
                    'Poli Gigi & Mulut',
                    'Poli Kulit & Estetika Medis',
                ],
                'featured_facilities' => [
                    'Laboratorium Darah Cepat (Hasil 45 Mnt)',
                    'USG 4D Kebidanan & Organ Perut',
                    'Klinik Gigi & Dental Panoramic',
                    'Farmasi Langsung Jadi',
                    'Vaksinasi Dewasa & Anak',
                ],
                'image_url' => 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'id' => 6,
                'name' => 'Klinik Utama Population BSD Serpong',
                'slug' => 'klinik-bsd',
                'facility_type' => 'Klinik Utama',
                'category_badge' => 'Klinik Spesialis & Diagnostic Center',
                'city' => 'Tangerang Selatan',
                'province' => 'Banten',
                'address' => 'Ruko Golden Boulevard Blok S-12, BSD City, Tangerang Selatan 15322',
                'distance_info' => 'Kawasan Pusat Bisnis & Hunian BSD City',
                'operating_hours' => 'Senin - Sabtu: 08.00 - 21.00 WIB · Minggu: 08.00 - 15.00 WIB',
                'phone' => '(021) 538-8900',
                'whatsapp' => '0811-9988-7766',
                'emergency_24h' => false,
                'bed_capacity' => 0,
                'doctor_count' => 20,
                'google_maps_url' => 'https://maps.google.com/?q=Klinik+Utama+Population+BSD+Serpong',
                'available_polis' => [
                    'Poli Umum',
                    'Poli Anak & Tumbuh Kembang',
                    'Poli Penyakit Dalam',
                    'Poli Mata',
                    'Poli Gigi & Mulut',
                ],
                'featured_facilities' => [
                    'Pemeriksaan X-Ray Digital',
                    'Laboratorium Darah & Urine Otomatis',
                    'Treadmill Test Jantung',
                    'Farmasi & Apotek Terpadu',
                    'Layanan Dokter ke Rumah (Homecare)',
                ],
                'image_url' => 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'id' => 7,
                'name' => 'Klinik Pratama Population Bintaro',
                'slug' => 'klinik-bintaro',
                'facility_type' => 'Klinik Pratama',
                'category_badge' => 'Fasilitas Kesehatan Tingkat Pertama (FKTP)',
                'city' => 'Tangerang Selatan',
                'province' => 'Banten',
                'address' => 'Jl. Bintaro Utama 3A No. 18, Sektor 3 Bintaro Jaya, Tangerang Selatan 15224',
                'distance_info' => 'Pelayanan Dokter Umum, Ibu & Anak, serta Faskes BPJS',
                'operating_hours' => '24 Jam Setiap Hari (Termasuk Hari Libur Nasional)',
                'phone' => '(021) 735-4422',
                'whatsapp' => '0811-9988-7777',
                'emergency_24h' => true,
                'bed_capacity' => 8,
                'doctor_count' => 14,
                'google_maps_url' => 'https://maps.google.com/?q=Klinik+Pratama+Population+Bintaro+Sektor+3',
                'available_polis' => [
                    'Poli Umum',
                    'Poli Gigi & Mulut',
                    'Poli Ibu & Anak (KIA/KB)',
                ],
                'featured_facilities' => [
                    'Tindakan Gawat Darurat Ringan 24 Jam',
                    'Pelayanan Faskes BPJS Kesehatan',
                    'Ambulans Transportasi Pasien',
                    'Pemeriksaan Gula Darah & Kolesterol Cepat',
                    'Ruang Observasi Sementara',
                ],
                'image_url' => 'https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'id' => 8,
                'name' => 'Klinik Pratama Population Kelapa Gading',
                'slug' => 'klinik-kelapa-gading',
                'facility_type' => 'Klinik Pratama',
                'category_badge' => 'Klinik Pratama 24 Jam & Faskes Keluarga',
                'city' => 'Jakarta Utara',
                'province' => 'DKI Jakarta',
                'address' => 'Jl. Boulevard Raya Blok FW No. 22, Kelapa Gading, Jakarta Utara 14240',
                'distance_info' => 'Akses Strategis Pusat Kelapa Gading',
                'operating_hours' => '24 Jam Non-Stop',
                'phone' => '(021) 4584-6677',
                'whatsapp' => '0811-9988-7788',
                'emergency_24h' => true,
                'bed_capacity' => 6,
                'doctor_count' => 12,
                'google_maps_url' => 'https://maps.google.com/?q=Klinik+Pratama+Population+Kelapa+Gading+Jakarta',
                'available_polis' => [
                    'Poli Umum',
                    'Poli Gigi & Mulut',
                    'Poli Kebidanan & Kandungan',
                ],
                'featured_facilities' => [
                    'Layanan Dokter Jaga 24 Jam',
                    'Farmasi Siaga 24 Jam',
                    'Fasilitas Rawat Luka & Jahit Minor',
                    'Layanan Vaksin & Imunisasi Anak',
                    'Skrining Kesehatan Keluarga',
                ],
                'image_url' => 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'id' => 9,
                'name' => 'Hospital Population Surabaya Barat',
                'slug' => 'surabaya-barat',
                'facility_type' => 'Rumah Sakit Utama',
                'category_badge' => 'RS Tipe B · Regional Jawa Timur',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'address' => 'Jl. Raya Bukit Darmo No. 88, Dukuh Pakis, Surabaya, Jawa Timur 60225',
                'distance_info' => 'Pusat Rujukan Regional Jawa Timur & Indonesia Timur',
                'operating_hours' => '24 Jam (IGD & Rawat Inap) · Poliklinik: 08.00 - 21.00 WIB',
                'phone' => '(031) 9920-1000',
                'whatsapp' => '0811-9988-7799',
                'emergency_24h' => true,
                'bed_capacity' => 200,
                'doctor_count' => 60,
                'google_maps_url' => 'https://maps.google.com/?q=Hospital+Population+Surabaya+Barat',
                'available_polis' => [
                    'Poli Jantung & Pembuluh Darah',
                    'Poli Bedah & Ortopedi',
                    'Poli Penyakit Dalam',
                    'Poli Anak & Tumbuh Kembang',
                    'Poli Saraf',
                    'Poli THT',
                ],
                'featured_facilities' => [
                    'IGD 24 Jam & Helipad Darurat',
                    'Cathlab Jantung & Pembuluh Darah',
                    'Pusat Bedah Tulang Belakang & Sendi',
                    'Laboratorium Terakreditasi Nasional',
                    'Layanan Fisioterapi Modern',
                ],
                'image_url' => 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'id' => 10,
                'name' => 'Hospital Population Denpasar Sunset',
                'slug' => 'denpasar-sunset',
                'facility_type' => 'Rumah Sakit Utama',
                'category_badge' => 'RS Internasional & Trauma Center Bali',
                'city' => 'Denpasar',
                'province' => 'Bali',
                'address' => 'Jl. Sunset Road No. 818, Kuta, Denpasar, Bali 80361',
                'distance_info' => 'Pusat Trauma & Wisata Medis (Medical Tourism)',
                'operating_hours' => '24 Jam Non-Stop (Layanan Pasien Domestik & Internasional)',
                'phone' => '(0361) 779-900',
                'whatsapp' => '0811-9988-7700',
                'emergency_24h' => true,
                'bed_capacity' => 160,
                'doctor_count' => 48,
                'google_maps_url' => 'https://maps.google.com/?q=Hospital+Population+Denpasar+Sunset+Road+Bali',
                'available_polis' => [
                    'Poli Umum & Medical Evacuation',
                    'Poli Bedah & Ortopedi',
                    'Poli Penyakit Dalam',
                    'Poli Jantung & Pembuluh Darah',
                    'Poli Gigi & Mulut',
                ],
                'featured_facilities' => [
                    'Unit Evakuasi Medis & Ambulans Udara',
                    'Pusat Trauma & Bedah Ortopedi Turis',
                    'Layanan Dokter Multi-Bahasa 24 Jam',
                    'Pusat Hiperbarik Oksigen (Hyperbaric Chamber)',
                    'Layanan Asuransi Internasional Direct Billing',
                ],
                'image_url' => 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=800&auto=format&fit=crop',
            ],
        ];

        // Daftar Kota / Wilayah untuk filter
        $cities = [
            'Semua Wilayah',
            'Tangerang',
            'Tangerang Selatan',
            'Jakarta Selatan',
            'Jakarta Barat',
            'Jakarta Pusat',
            'Jakarta Utara',
            'Surabaya',
            'Denpasar',
        ];

        // Daftar Kategori Fasilitas untuk filter badge
        $facilityTypes = [
            'Semua',
            'IGD 24 Jam',
            'Rumah Sakit Utama',
            'Klinik Utama',
            'Klinik Pratama',
        ];

        return Inertia::render('Clinic/Location', [
            'clinics' => $clinics,
            'cities' => $cities,
            'facilityTypes' => $facilityTypes,
        ]);
    }
}
